# Generated by Django 5.1.6 on 2025-03-15 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_publication_year_book_publication_yearx'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='publication_yearx',
            new_name='publication_year',
        ),
    ]
